name: bombcell
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=25.2
  - pip:
    - pandas==2.3.3
    - git+https://github.com/benjamin-heasly/bombcell#subdirectory=py_bombcell
    - numpy==2.2.6
